{
 "title": "03. User Activity (Filter by Wallet)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "wallet_address",
    "label": "wallet_address",
    "query": "SELECT wallet FROM onboarding_profile_view;"
   }
  ]
 },
 "panels": [
  {
   "title": "WALLETS CONNECTED = UNIQUE USERS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  --p.timestamp AS \"TIME\",\n  p.wallet AS \"WALLET\",\n  p.profile_id AS \"PROFILE_ID\",\n  p.utm_source AS \"SOURCE\",\n  p.utm_medium AS \"MEDIUM\",\n  p.utm_campaign AS \"CAMPAIGN\",\n  SUM(a.volume) AS \"VOLUME\",\n  SUM(a.fee) AS \"FEES\"\nFROM\n  onboarding_profile_view p\nLEFT JOIN\n  app_fill_1d a ON a.profile_id = p.profile_id\n--LEFT JOIN\n  --analytic_event e ON ((e.event->>'response_body')::jsonb->'result'->0->'profile'->>'id')::bigint = p.profile_id\nWHERE\n  p.wallet IN ($wallet_address)\n  --profile_id IN ($profile_id)\nGROUP BY\n  1,2,3,4,5\nORDER BY\n  2 ASC;\n--LIMIT 100;"
    }
   ]
  },
  {
   "title": "ORDERS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.timestamp AS \"TIME\",\n  p.wallet AS \"WALLET\",\n  --p.profile_id AS \"PROFILE_ID\",\n  --p.utm_source AS \"SOURCE\",\n  --p.utm_medium AS \"MEDIUM\",\n  --p.utm_campaign AS \"CAMPAIGN\",\n  a.market_id AS \"MARKET\",\n  a.side AS \"SIDE\",\n  a.order_type AS \"ORDER TYPE\",\n  a.status AS \"STATUS\",\n  a.price AS \"PRICE\",\n  a.size AS \"SIZE\",\n  a.size*a.price AS \"VOLUME\"\n  --a.initial_size AS \"INITIAL SIZE\",\n  --a.total_filled_size AS \"FILLED SIZE\",\n  --a.reason AS \"REASON\"\nFROM\n  onboarding_profile_view p\nINNER JOIN\n  app_order a ON a.profile_id = p.profile_id\nWHERE\n  wallet IN ($wallet_address)\n--ORDER BY\n  --1 DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "FILLS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.timestamp AS \"TIME\",\n  p.wallet AS \"WALLET\",\n  --p.profile_id AS \"PROFILE_ID\",\n  --p.utm_source AS \"SOURCE\",\n  --p.utm_medium AS \"MEDIUM\",\n  --p.utm_campaign AS \"CAMPAIGN\",\n  a.market_id AS \"MARKET\",\n  a.side AS \"SIDE\",\n  a.is_maker AS \"IS MAKER\",\n  a.price AS \"PRICE\",\n  a.size AS \"SIZE\",\n  a.size*a.price AS \"VOLUME\",\n  a.fee AS \"FEES\",\n  a.liquidation AS \"LIQUIDATION\"\nFROM\n  onboarding_profile_view p\nINNER JOIN\n  app_fill a ON a.profile_id = p.profile_id\nWHERE\n  p.wallet IN ($wallet_address)\nORDER BY\n  1 DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "DEPOSITS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.timestamp AS \"TIME\",\n  p.wallet AS \"WALLET\",\n  --p.profile_id AS \"PROFILE_ID\",\n  --p.utm_source AS \"SOURCE\",\n  --p.utm_medium AS \"MEDIUM\",\n  --p.utm_campaign AS \"CAMPAIGN\",\n  a.amount AS \"AMOUNT\",\n  a.status AS \"STATUS\"\nFROM\n  onboarding_profile_view p\nINNER JOIN\n  app_balance_operation a ON a.profile_id = p.profile_id\nWHERE\n  a.ops_type = 'deposit' AND\n  p.wallet IN ($wallet_address)\nORDER BY\n  1 DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "WITHDRAWALS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  p.timestamp AS \"TIME\",\n  p.wallet AS \"WALLET\",\n  --p.profile_id AS \"PROFILE_ID\",\n  --p.utm_source AS \"SOURCE\",\n  --p.utm_medium AS \"MEDIUM\",\n  --p.utm_campaign AS \"CAMPAIGN\",\n  a.amount AS \"AMOUNT\",\n  a.status AS \"STATUS\"\nFROM\n  onboarding_profile_view p\nINNER JOIN\n  app_balance_operation a ON a.profile_id = p.profile_id\nWHERE\n  a.ops_type = 'withdrawal' AND\n  p.wallet IN ($wallet_address)\nORDER BY\n  1 DESC\nLIMIT 100;"
    }
   ]
  }
 ]
}