{
 "title": "Deposit/Withdrawal",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Fee withdrawals",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), * FROM app_balance_operation WHERE (ops_type = 'withdrawal') \nand profile_id = 3\nORDER BY timestamp DESC\nLIMIT 50"
    }
   ]
  },
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Deposits/Withdrawals",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT ops_type, SUM(amount) \nFROM app_balance_operation \n/*ops_type not in ('pnl', 'funding','fee')*/\nWHERE ops_type in ('deposit', 'credit', 'withdrawal', 'withdraw_credit', 'withdraw_fee', 'referral_payout') and status !='pending'\nGROUP BY ops_type;"
    }
   ]
  },
  {
   "title": "Pending deposits",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), * FROM app_balance_operation \r\nWHERE (ops_type = 'deposit' AND status!='success' AND txhash != '0xbe4736a009a8d55e0b46ed27feb12abdf824580348a146826ea9cc8fdd5bb827') \r\nORDER BY timestamp DESC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "> 1 pending withdrawals anomaly",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT profile_id, count(amount) as pending_count \r\nFROM app_balance_operation \r\nWHERE (status = 'pending' AND ops_type = 'withdrawal')\r\nGROUP BY profile_id\r\nHAVING count(amount) > 1\r\nORDER BY count(amount) DESC;"
    }
   ]
  },
  {
   "title": "Pending Withdrawals",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), ops_type, status, amount, profile_id, wallet FROM app_balance_operation \r\nWHERE (ops_type = 'withdrawal' AND status='pending') \r\nORDER BY timestamp DESC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "All withdrawals",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), * FROM app_balance_operation WHERE (ops_type = 'withdrawal') \r\nORDER BY timestamp DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "All deposits",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), ops_type,status,  amount, wallet, profile_id, ops_id2, shard_id FROM app_balance_operation \r\n WHERE (ops_type = 'deposit') \r\n ORDER BY timestamp DESC\r\n LIMIT 50"
    }
   ]
  }
 ]
}