{
 "title": "Insurance",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "symbol",
    "query": "select distinct(market_id) from app_fill"
   }
  ]
 },
 "panels": [
  {
   "title": "Insurance Pnl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), sum(amount)\r\nFROM app_balance_operation \r\nWHERE profile_id=0 and timestamp > $__from::bigint*1000 and status='success' and ops_type in ('pnl', 'funding', 'fee')\r\nGROUP BY timestamp, shard_id\r\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "Inv3 (fast load)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * from get_last_inv3_data();"
    }
   ]
  },
  {
   "title": "Invariant#3 ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select to_timestamp(last_updated/1e6),id,valid,margined_ae_sum,exchange_balance,insurance_balance,archive_id,archive_timestamp \nfrom app_inv3_data_by_last_updated where last_updated > 1703804087000000\nORDER BY last_updated DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Insurance account Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  t1.id AS profile_id, t1.balance, t1.account_equity, t1.cum_unrealized_pnl AS unrealized_pnl, t1.account_margin,\n  TO_TIMESTAMP(t1.last_update/1000000::numeric) AS last_update\nFROM app_profile_cache_last t1\nWHERE t1.id = 0"
    }
   ]
  },
  {
   "title": "Insurance LIVE positions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  t1.market_id, t1.profile_id, t1.size, t1.side, t1.entry_price, t1.unrealized_pnl, t1.notional, t1.margin, t1.liquidation_price, t1.fair_price\nFROM app_position_last_archive_timestamp last\nJOIN app_position t1 ON t1.market_id = last.market_id AND t1.archive_timestamp = last.archive_timestamp\n"
    }
   ]
  },
  {
   "title": "Insurance OPEN orders",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side,  status, initial_size, total_filled_size, reason  FROM app_order \nWHERE profile_id = 0 and status ='open'\nORDER BY timestamp DESC"
    }
   ]
  },
  { "title": "Liquidations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "All Time Partial Liquidations",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT market_id, sum(price*size)/2 as volume FROM app_fill \nWHERE liquidation=true and trade_id!='wf3'\nGROUP BY market_id\nLIMIT 100"
    }
   ]
  },
  {
   "title": "All Time Insurance Liquidations",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT market_id, sum(price*size)/2 as volume FROM app_fill \nWHERE liquidation=true and trade_id='wf3'\nGROUP BY market_id\nLIMIT 100"
    }
   ]
  },
  { "title": "Insurance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$symbol Fills",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side, is_maker, order_id, fee, liquidation FROM app_fill \r\nWHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol) AND profile_id = 0\r\nORDER BY timestamp DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "$symbol Orders",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side,  status, initial_size, total_filled_size, reason  FROM app_order \r\nWHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id in ($symbol) AND profile_id = 0 \r\nORDER BY timestamp DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Balance Ops",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), status, ops_type, amount, reason, txhash, profile_id \r\nFROM app_balance_operation \r\nWHERE profile_id=0 AND timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 \r\nORDER BY timestamp DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Balance Ops Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT shard_id,ops_type, SUM(amount) \r\nFROM app_balance_operation \r\nWHERE profile_id = 0 and status!='pending'\r\n\r\nGROUP BY ROLLUP(ops_type), rollup(shard_id) ORDER BY shard_id, ops_type\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Balance Ops",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\ttime_bucket('1 hour'::interval, to_timestamp(timestamp/1e6)) AS hour_bucket, \r\n\tto_timestamp(timestamp/1e6) as timestamp, \r\n\tsum(amount) AS Amount, \r\n\tshard_id \r\nFROM app_balance_operation \r\nWHERE profile_id = 0 \r\nand ops_type='pnl'\r\nGROUP BY 1, 2, shard_id\r\nORDER BY hour_bucket DESC"
    }
   ]
  },
  {
   "title": "wf3_insurance",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), profile_id, market_id, order_id, price, sum(size), side\r\nFROM app_fill \r\nWHERE profile_id !=0 AND order_id ='wf3'\r\n\r\nGROUP BY timestamp,market_id,order_id,price,side, profile_id\r\nORDER BY timestamp DESC\r\nLIMIT 100\r\n"
    }
   ]
  }
 ]
}