{
 "title": "Liquidations",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "limit", "label": "row limit", "query": "100, 1000, 10000" },
   {
    "name": "time_interval",
    "label": "time interval",
    "query": "1m,10m,30m,1h,6h,12h, 24h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Accounts with Equity < 0",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": " SELECT\n  t1.id AS profile_id, t1.balance, t1.account_equity, t1.cum_unrealized_pnl AS unrealized_pnl, t1.account_margin,\n  TO_TIMESTAMP(t1.last_update/1000000::numeric) AS last_update\nFROM\n  app_profile_cache_last t1\nWHERE t1.account_equity < -1\n"
    }
   ]
  },
  {
   "title": "Accounts with margin < 2%",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  t1.id AS profile_id, t1.balance, t1.account_equity, t1.cum_unrealized_pnl AS unrealized_pnl, t1.account_margin,\n  TO_TIMESTAMP(t1.last_update/1000000::numeric) AS last_update\nFROM\n  app_profile_cache_last t1\nWHERE t1.account_margin < 0.02\nORDER BY t1.account_margin DESC;"
    }
   ]
  },
  {
   "title": "Accounts with margin < 5%",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  t1.id AS profile_id, t1.balance, t1.account_equity, t1.cum_unrealized_pnl AS unrealized_pnl, t1.account_margin,\n  TO_TIMESTAMP(t1.last_update/1000000::numeric) AS last_update\nFROM\n  app_profile_cache_last t1\nWHERE t1.account_margin < 0.05\nORDER BY t1.account_margin DESC;"
    }
   ]
  },
  {
   "title": "wf3 liquidations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, sum(price*size) as volume \r\nFROM app_fill \r\nwhere order_id='wf3' and profile_id=0 and timestamp >= $__from::bigint*1000\r\ngroup by rollup(symbol)"
    }
   ]
  },
  {
   "title": "wf1 liquidations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, sum(price*size)/2 as volume \r\nFROM app_fill \r\nwhere liquidation=true and profile_id!=0 and timestamp>=$__from::bigint*1000\r\ngroup by rollup(symbol)"
    }
   ]
  },
  {
   "title": "Latest Open Positions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  t1.market_id, t1.profile_id, t1.size, t1.side, t1.entry_price, t1.unrealized_pnl, t1.notional, t1.margin, t1.liquidation_price, t1.fair_price,\r\n  to_timestamp(t1.archive_timestamp/1e6) AS archive_timestamp\r\nFROM app_position_last_archive_timestamp last\r\nJOIN app_position t1 ON t1.market_id = last.market_id AND t1.archive_timestamp = last.archive_timestamp\r\n"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Users wf1",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT to_timestamp(timestamp/1e6) as timestamp, market_id, price, size, side, profile_id, liquidation,is_maker, fee, order_id, trade_id\r\n FROM app_fill \r\n WHERE (liquidation = true AND order_id != 'wf3' AND profile_id!=0) \r\n ORDER BY timestamp DESC\r\n LIMIT $limit"
    }
   ]
  },
  {
   "title": "Insurance wf3",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side, profile_id, is_maker, fee, liquidation, order_id FROM app_fill \nWHERE order_id != 'clawback' AND order_id = 'wf3' \nORDER BY timestamp DESC\nLIMIT 100",
     "legendFormat": "__auto",
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side, profile_id, is_maker, fee, liquidation, order_id FROM app_fill \r\nWHERE order_id != 'clawback' AND order_id = 'wf3' and profile_id=0\r\nORDER BY timestamp DESC\r\nLIMIT $limit"
    }
   ]
  },
  {
   "title": "Users wf3",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6) as timestamp, market_id, price, size, side, profile_id, is_maker, fee, order_id\r\n FROM app_fill \r\n WHERE (order_id = 'wf3' AND profile_id!=0) \r\n ORDER BY timestamp DESC\r\n LIMIT $limit"
    }
   ]
  },
  {
   "title": "Insurance clawbacks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side, is_maker, fee, liquidation, order_id FROM app_fill \r\nWHERE profile_id = 0 AND order_id = 'clawback' \r\nORDER BY timestamp DESC\r\nLIMIT $limit"
    }
   ]
  }
 ]
}