{
 "title": "Market Info",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "symbol",
    "query": "select distinct(market_id) from app_fill"
   },
   {
    "name": "time_interval",
    "label": "time interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cumulative volume",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT market_id as symbol, SUM(volume) as volume\r\nFROM app_trade_volume_1d\r\nGROUP BY ROLLUP(symbol)"
    }
   ]
  },
  {
   "title": "$time_interval volume",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, SUM(size*price) as volume\r\nFROM app_trade\r\nWHERE timestamp >= (\r\n    EXTRACT(\r\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '$time_interval'\r\n    ) * 1000000\r\n  )::bigint\r\nGROUP BY ROLLUP(symbol)"
    }
   ]
  },
  {
   "title": "1d volume(for cheng use)",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id, SUM(size*price) as volume\nFROM app_fill\nWHERE timestamp >= (\n    EXTRACT(\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '$time_interval'\n    ) * 1000000\n  )::bigint\nand profile_id not in (select profile_id from ignored_profile_ids)\ngroup by rollup(market_id)\n"
    }
   ]
  },
  {
   "title": "OI (for cheng use)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  t5.market_id,\r\n  sum(notional) AS sum_notional \r\nFROM app_position t5\r\nJOIN app_position_last_archive_timestamp t4 ON\r\n  t5.market_id=t4.market_id AND t5.archive_timestamp=t4.archive_timestamp\r\nwhere t5.side = 'long'\r\nAND t5.profile_id NOT IN (select profile_id from ignored_profile_ids)\r\nGROUP BY t5.market_id;"
    }
   ]
  },
  {
   "title": "Exchange TVL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), SUM(\r\n  CASE WHEN ops_type ='deposit' THEN amount\r\n  WHEN ops_type = 'withdrawal' THEN -amount\r\n  END) as net_deposits\r\nFROM app_balance_operation \r\nWHERE ops_type in ('deposit', 'withdrawal') and status not in ('pending')\r\ngroup by timestamp\r\norder by timestamp desc"
    }
   ]
  },
  {
   "title": "1d Active Traders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1d'::interval, to_timestamp(bucket/1e6)) group_bucket, count(distinct(profile_id)) \r\nFROM app_fill_profile_1d\r\nWHERE bucket > $__unixEpochFrom()::bigint*1000000\r\nGROUP BY group_bucket\r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "7d Active Traders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('7d'::interval, to_timestamp(bucket/1e6)) group_bucket, count(distinct(profile_id)) \r\nFROM app_fill_profile_1d\r\nWHERE bucket > $__unixEpochFrom()::bigint*1000000\r\nGROUP BY group_bucket\r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "Funding Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(amount) < 1 as funding_zero_sum FROM app_balance_operation \r\nWHERE ops_type='funding'"
    }
   ]
  },
  {
   "title": "Deposited Wallets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(wallet)) FROM app_balance_operation \r\nWHERE ops_type='deposit'\r\n"
    }
   ]
  },
  {
   "title": "$time_interval Deposited Wallets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(wallet)) FROM app_balance_operation \r\nWHERE ops_type='deposit' \r\nAND timestamp >= (\r\n    EXTRACT(\r\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '$time_interval'\r\n    ) * 1000000\r\n  )::bigint"
    }
   ]
  },
  {
   "title": "Net Deposits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\r\n  CASE WHEN ops_type ='deposit' THEN amount\r\n  WHEN ops_type = 'withdrawal' THEN -amount\r\n  END) as net_deposits\r\nFROM app_balance_operation \r\nWHERE ops_type in ('deposit', 'withdrawal') and status !='pending';"
    }
   ]
  },
  {
   "title": "$time_interval Withdrawn Wallets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(wallet)) FROM app_balance_operation \r\nWHERE ops_type='withdrawal' \r\nAND timestamp >= (\r\n    EXTRACT(\r\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '$time_interval'\r\n    ) * 1000000\r\n  )::bigint"
    }
   ]
  },
  {
   "title": "7d Active traders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(profile_id)) \r\n FROM app_fill\r\n WHERE timestamp >= (\r\n    EXTRACT(\r\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '7 days'\r\n    ) * 1000000\r\n  )::bigint"
    }
   ]
  },
  {
   "title": "1d Active Traders",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(profile_id))\r\n FROM app_fill\r\n WHERE timestamp >= (\r\n    EXTRACT(\r\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '1 days'\r\n    ) * 1000000\r\n  )::bigint"
    }
   ]
  },
  {
   "title": "Total fee",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, sum(-1*fee)\r\nFROM app_fill_fee_1d \r\ngroup by rollup(market_id)\r\n"
    }
   ]
  },
  {
   "title": "$time_interval wf3 liquidations",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, sum(price*size) as volume FROM app_fill \r\nwhere order_id='wf3' \r\nand profile_id=0 \r\nand timestamp >= (\r\n    EXTRACT(\r\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '$time_interval'\r\n    ) * 1000000\r\n  )::bigint\r\n\r\ngroup by rollup(symbol)"
    }
   ]
  },
  {
   "title": "$time_interval fees",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, sum(-1*fee) as fees\r\nFROM app_fill \r\nWHERE timestamp >= (\r\n    EXTRACT(\r\n        EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '$time_interval'\r\n    ) * 1000000\r\n  )::bigint\r\ngroup by rollup(market_id)\r\nORDER BY fees DESC"
    }
   ]
  },
  { "title": "Market Trades/Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Market Trades",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, profile_id, price, size, (price*size) as notional, side, is_maker, fee, liquidation, order_id FROM app_fill \r\nWHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol) and size > 0.001 \r\nORDER BY \"timestamp\" DESC \r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "External Market Trades",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, profile_id, price, size, (price*size) as notional, side, is_maker, fee, liquidation, order_id FROM app_fill \r\nWHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol) and size > 0.001 and profile_id not in (select profile_id from ignored_profile_ids)\r\nORDER BY \"timestamp\" DESC \r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Market Orders",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, profile_id, order_type, status, price, size, side, initial_size, total_filled_size, reason FROM app_order \r\nWHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol)\r\nORDER BY timestamp DESC\r\nLIMIT 100"
    }
   ]
  }
 ]
}