{
 "title": "MM Orders and Trades",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "symbol",
    "label": "symbol",
    "query": "select distinct(market_id) from app_order"
   },
   {
    "name": "profile",
    "label": "profile",
    "query": "DELTIX_BINANCE : 14919, OTHER : 20, SELINI_1 : 2104,  SELINI_2 : 12071, SELINI_3 : 12072, CrypPro : 12483, Moonvault_1 : 13436, Moonvault_2 : 12472, Moonvault_3 : 16510, Moonvault_4 : 16955, Finlink : 12505, Vovega : 15679, Adaptive : 17217"
   }
  ]
 },
 "panels": [
  {
   "title": "Realised PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), sum(amount)\r\nFROM app_balance_operation \r\nWHERE profile_id in ($profile) and timestamp > $__from::bigint*1000 and status='success' and ops_type in ('pnl', 'funding', 'fee')\r\nGROUP BY timestamp\r\nORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "Position Risk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(archive_timestamp/1e6), market_id, (CASE WHEN side='long' THEN notional ELSE -1*notional END) AS notional \r\nfrom app_position where profile_id IN ($profile) and market_id in ($symbol) and archive_timestamp >= (EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - INTERVAL '48 hour')) * 1000000)::bigint"
    }
   ]
  },
  {
   "title": "MM account Info ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  t1.id AS profile_id, t1.wallet, t1.balance, t1.account_equity, t1.cum_unrealized_pnl AS unrealized_pnl, t1.withdrawable_balance, t1.health, t1.account_leverage, t1.cum_trading_volume,\n  t1.total_position_margin, t1.total_order_margin, \n  TO_TIMESTAMP(t1.last_update/1000000::numeric) AS last_update\nFROM app_profile_cache_last t1\nWHERE t1.id IN ($profile)\n"
    }
   ]
  },
  {
   "title": "Open positions ",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  t1.market_id,\n  t1.profile_id,\n  t1.size,\n  t1.side,\n  t1.entry_price,\n  t1.unrealized_pnl,\n  (\n    CASE\n      WHEN t1.side = 'long' THEN t1.notional\n      ELSE -1 * t1.notional\n    END\n  ) as notional,\n  t1.margin,\n  t1.fair_price,\n  t1.liquidation_price,\n  to_timestamp(t1.archive_timestamp / 1e6) AS archive_timestamp\nFROM app_position_last_archive_timestamp last\nJOIN app_position t1 ON t1.market_id = last.market_id AND t1.archive_timestamp = last.archive_timestamp"
    }
   ]
  },
  {
   "title": "Maker Volume",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n market_id, \r\n SUM(price*size) AS volume\r\n FROM app_fill\r\n WHERE profile_id IN ($profile) AND market_id IN ($symbol) AND is_maker=true AND timestamp > $__from::bigint*1000\r\n GROUP BY rollup(market_id)\r\n"
    }
   ]
  },
  {
   "title": "Taker Volume",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n market_id, \r\n SUM(price*size) AS volume\r\n FROM app_fill\r\n WHERE profile_id IN ($profile) AND market_id IN ($symbol) AND is_maker=false AND timestamp > $__from::bigint*1000\r\n GROUP BY rollup(market_id)\r\n"
    }
   ]
  },
  {
   "title": "Orders Count",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT market_id, count(status), profile_id FROM app_order \r\nWHERE status = 'open' AND profile_id in ($profile) AND timestamp > $__from::bigint*1000\r\nGROUP BY market_id, profile_id"
    }
   ]
  },
  {
   "title": "MM Bot spreads",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH best_bids AS (\r\n  SELECT market_id, max(price) as best_bid_price FROM app_order \r\n  WHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol) AND profile_id in ($profile) AND status='open' AND side='long'\r\n  GROUP BY market_id\r\n),\r\nbest_asks AS (\r\n  SELECT market_id, min(price) as best_ask_price FROM app_order \r\n  WHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol) AND profile_id in ($profile) AND status='open' AND side='short'\r\n  GROUP BY market_id\r\n)\r\n\r\nSELECT b.market_id,\r\n       b.best_bid_price,\r\n       a.best_ask_price,\r\n       (a.best_ask_price - b.best_bid_price)/(b.best_bid_price/2+a.best_ask_price/2) AS spread\r\nFROM best_bids b\r\nJOIN best_asks a\r\nON b.market_id = a.market_id\r\nORDER BY b.market_id;"
    }
   ]
  },
  { "title": "Orders and Trades", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "MM Fills (excl small trades)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, profile_id, price, size, price*size AS notional, side, is_maker, fee, liquidation, order_id, trade_id\r\n FROM app_fill \r\n WHERE profile_id IN ($profile) AND timestamp > $__from::bigint*1000 AND price*size > 10 AND market_id IN ($symbol) AND timestamp <= $__to::bigint*1000\r\n order by timestamp DESC\r\n LIMIT 100"
    }
   ]
  },
  {
   "title": "MM Bids",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT to_timestamp(timestamp/1e6) as timestamp, market_id, status, price, size, price*size AS notional, side, initial_size, total_filled_size, profile_id, order_type, reason, id FROM app_order \r\nWHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol) AND profile_id in ($profile) AND status='open' AND side='long'\r\nORDER BY timestamp DESC, price DESC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "MM Asks",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, status, price, size, price*size AS notional, side, initial_size, total_filled_size, profile_id, order_type, reason, id FROM app_order \r\nWHERE timestamp >= $__from::bigint*1000 AND timestamp <= $__to::bigint*1000 AND market_id IN ($symbol) AND profile_id in($profile)  AND status='open' AND side='short'\r\nORDER BY timestamp DESC, price ASC"
    }
   ]
  },
  {
   "title": "Summary Balance Operations",
   "type": "table",
   "description": "funding \npnl \nfee",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT shard_id,ops_type, SUM(amount) \nFROM app_balance_operation \nWHERE profile_id in ($profile) and status='success'\n\nGROUP BY ROLLUP(ops_type),rollup(shard_id) ORDER BY shard_id, ops_type\n"
    }
   ]
  },
  {
   "title": "Historical Realized Pnl",
   "type": "table",
   "description": "funding \npnl \nfee",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('1 day'::interval, to_timestamp(timestamp/1e6)) as day_bucket, \n\tsum(amount) AS Amount, \n\tshard_id\nFROM app_balance_operation \nWHERE profile_id in ($profile) \n\tand ops_type in ('pnl', 'funding', 'fee')\nGROUP BY day_bucket, shard_id\nORDER BY day_bucket DESC"
    }
   ]
  }
 ]
}