{
 "title": "Playground",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "time_interval", "label": "time interval", "query": "15m, 1h, 12h, 24h, 7d" },
   { "name": "symbol", "query": "BTC-USD, ETH-USD, SOL-USD" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side, profile_id, is_maker, fee, liquidation, order_id FROM app_fill \nWHERE order_id = 'clawback'\nORDER BY timestamp DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "$time_interval liquidations",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, sum(price*size) as volume\r\nFROM app_trade \r\nWHERE timestamp >= (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '$time_interval') * 1000000)::bigint\r\nAND liquidation=true\r\nGROUP BY ROLLUP(symbol)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, price, size, side, profile_id, is_maker, fee, liquidation, order_id FROM app_fill \nWHERE order_id != 'clawback' AND order_id = 'wf3' \nORDER BY timestamp DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT profile_id, SUM(volume) as notional\r\nFROM app_fill_1d\r\nwhere profile_id not in (select profile_id from ignored_profile_ids)\r\ngroup by profile_id"
    }
   ]
  },
  {
   "title": "Cumulative Volume",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, SUM(volume) as volume\r\nFROM app_trade_market_1d \r\nGROUP BY ROLLUP(symbol)"
    }
   ]
  },
  {
   "title": "24hr volume",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT market_id as symbol, SUM(volume) as volume\r\nFROM app_trade_market_1h \r\nWHERE timestamp >= (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP - INTERVAL '24 hours') * 1000000)::bigint\r\nGROUP BY ROLLUP(symbol)\r\n"
    }
   ]
  },
  { "title": "Insurance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Insurance Fills",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(timestamp/1e6), market_id, order_id, price, size, side, is_maker, fee, liquidation  FROM app_fill WHERE market_id = 'BTC-USD' AND profile_id = 0 ORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "Insurance Fills",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT  to_timestamp(timestamp/1e6), market_id, order_id, price, size, side, is_maker, fee, liquidation  FROM app_fill WHERE market_id = 'ETH-USD' AND profile_id = 0 ORDER BY timestamp DESC"
    }
   ]
  },
  {
   "title": "Insurance Fills",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT  to_timestamp(timestamp/1e6), market_id, order_id, price, size, side, is_maker, fee, liquidation  FROM app_fill WHERE market_id = 'SOL-USD' AND profile_id = 0 ORDER BY timestamp DESC"
    }
   ]
  }
 ]
}