{
 "title": "Referral",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "sanity check: sum(payout) < sum(fee)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    COALESCE(af.referral_profile_id, rp.profile_id) AS profile_id,\r\n    COALESCE(af.total_fee, 0) AS total_fee,\r\n    COALESCE(rp.total_payout_amount, 0) AS total_payout_amount\r\nFROM\r\n    (\r\n        SELECT\r\n            app_referral_link.profile_id AS referral_profile_id,\r\n            SUM(app_fill.fee) AS total_fee\r\n        FROM\r\n            app_referral_link\r\n        INNER JOIN\r\n            app_fill ON app_referral_link.invited_ID = app_fill.profile_id\r\n        GROUP BY\r\n            app_referral_link.profile_id\r\n    ) af\r\nFULL JOIN\r\n    (\r\n        SELECT\r\n            profile_id,\r\n            TRUE AS processed,\r\n            SUM(amount) AS total_payout_amount\r\n        FROM\r\n            referral_payout\r\n        GROUP BY\r\n            profile_id\r\n    ) rp ON af.referral_profile_id = rp.profile_id AND rp.processed\r\nORDER BY\r\n    profile_id;\r\n"
    }
   ]
  },
  {
   "title": "trading fee for each sign up (A)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    app_referral_link.profile_id AS referral_profile_id,\r\n    app_referral_link.invited_ID,\r\n    app_fill.market_id,\r\n    app_fill.fee,\r\n    CASE WHEN GROUPING(app_fill.fee) = 1 THEN SUM(app_fill.fee) END AS total_fee\r\nFROM\r\n    app_referral_link\r\nINNER JOIN\r\n    app_fill ON app_referral_link.invited_ID = app_fill.profile_id\r\nGROUP BY\r\n    GROUPING SETS (\r\n        (app_referral_link.profile_id, app_referral_link.invited_ID, app_fill.market_id, app_fill.fee),\r\n        (app_referral_link.profile_id, app_referral_link.invited_ID, app_fill.market_id)\r\n    )\r\nORDER BY\r\n    referral_profile_id, invited_ID, market_id;\r\n"
    }
   ]
  },
  {
   "title": "referral volume and referral fees for each wallet referred",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    app_referral_link.profile_id AS referral_profile_id,\r\n    app_referral_link.invited_ID,\r\n    wallet.wallet,\r\n    SUM(app_fill_1d.fee) as total_fee,\r\n    SUM(app_fill_1d.volume) as total_volume\r\nFROM\r\n    app_referral_link\r\nINNER JOIN\r\n    app_fill_1d ON app_fill_1d.profile_id = app_referral_link.invited_ID\r\nINNER JOIN\r\n    app_profile as wallet ON wallet.id = app_referral_link.invited_ID\r\nGROUP BY\r\n    1,2,3\r\nORDER BY\r\n    referral_profile_id, invited_ID;\r\n"
    }
   ]
  },
  {
   "title": "sign up breakdown",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select * from app_referral_link order by profile_id;"
    }
   ]
  },
  {
   "title": "volume breakdown for each sign up ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    app_referral_link.profile_id AS referral_profile_id,\r\n    app_referral_link.invited_ID,\r\n    app_fill.market_id,\r\n    SUM(app_fill.price * app_fill.size) AS volume\r\nFROM\r\n    app_referral_link\r\nINNER JOIN\r\n    app_fill ON app_referral_link.invited_ID = app_fill.profile_id\r\nGROUP BY\r\n    app_referral_link.profile_id, app_referral_link.invited_ID, app_fill.market_id\r\nUNION ALL\r\nSELECT\r\n    app_referral_link.profile_id,\r\n    app_referral_link.invited_ID,\r\n    'Total' AS market_id,\r\n    SUM(app_fill.price * app_fill.size) AS volume\r\nFROM\r\n    app_referral_link\r\nINNER JOIN\r\n    app_fill ON app_referral_link.invited_ID = app_fill.profile_id\r\nGROUP BY\r\n    app_referral_link.profile_id, app_referral_link.invited_ID\r\nORDER BY\r\n    referral_profile_id, invited_ID, market_id;\r\n"
    }
   ]
  },
  {
   "title": "Payouts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "select profile_id, processed, sum(amount) from referral_payout group by profile_id, processed;"
    }
   ]
  },
  {
   "title": "Payout history",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    { "rawSql": "select * from referral_payout" }
   ]
  },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "select * from referral_volumes;"
    }
   ]
  },
  {
   "title": "Sign_ups",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "select * from app_referral_counter;"
    }
   ]
  }
 ]
}