{
 "title": "Selini trade metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "counter_party",
    "label": "counter_party",
    "query": "SELINI_1 : 2104,  SELINI_2 : 12071, SELINI_3 : 12072, CrypPro : 12483, Moonvault_1 : 13436, Moonvault_2 : 12472, Vovega : 15679"
   }
  ]
 },
 "panels": [
  {
   "title": "Selini notional traded against mm bot",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  to_timestamp(t2.timestamp/1e6), \n  t2.market_id, \n  SUM(CASE WHEN t2.side='long' THEN t2.price*t2.size ELSE -t2.price*t2.size END) AS net_notional\nFROM\n(\n  SELECT * \n  FROM app_fill \n  WHERE profile_id in (13,14,15,1561,11002,11007,704,11831) \n  and timestamp >= $__from::bigint*1000\n) t1,\n(\n  SELECT * \n  FROM app_fill\n  WHERE profile_id in ($counter_party) \n  and timestamp >= $__from::bigint*1000\n) t2\nWHERE t2.trade_id=t1.trade_id\nGROUP BY t2.market_id, t2.timestamp\n"
    }
   ]
  },
  {
   "title": "mm bot notional traded against Selini",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  to_timestamp(t1.timestamp/1e6), \n  t1.market_id, \n  SUM(CASE WHEN t1.side='long' THEN t1.price*t1.size ELSE -t1.price*t1.size END) AS net_notional\nFROM\n(\n  SELECT * \n  FROM app_fill \n  WHERE profile_id in (13,14,15,1561,11002,11007,704,11831) \n  and timestamp >= $__from::bigint*1000\n) t1,\n(\n  SELECT * \n  FROM app_fill\n  WHERE profile_id in ($counter_party) \n  and timestamp >= $__from::bigint*1000\n) t2\nWHERE t2.trade_id=t1.trade_id\nGROUP BY t1.market_id, t1.timestamp\n"
    }
   ]
  },
  {
   "title": "Trades against Selini",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(t2.timestamp/1e6), t2.market_id, t2.profile_id, t2.price, t2.size, t2.price*t2.size AS notional, t2.side, t2.is_maker, t2.fee, t2.liquidation, t2.order_id, t2.trade_id \nfrom \n(\n  SELECT * \n  FROM app_fill \n  WHERE profile_id in (13,14,15,1561,11002,11007,704,11831) \n  and timestamp >= $__from::bigint*1000\n) t1,\n(\n  SELECT * \n  FROM app_fill\n  WHERE profile_id in ($counter_party) \n  and timestamp >= $__from::bigint*1000\n) t2\nWHERE t2.trade_id=t1.trade_id;"
    }
   ]
  },
  {
   "title": "Selini notional traded",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT t2.market_id, sum(t2.price*t2.size) AS notional \nfrom \n(\n  SELECT * \n  FROM app_fill \n  WHERE profile_id in (13,14,15,1561,11002,11007,704,11831) \n  and timestamp >= $__from::bigint*1000\n) t1,\n(\n  SELECT * \n  FROM app_fill\n  WHERE profile_id in ($counter_party) \n  and timestamp >= $__from::bigint*1000\n) t2\nWHERE t2.trade_id=t1.trade_id\nGROUP BY rollup(t2.market_id);\n"
    }
   ]
  },
  {
   "title": "Selini notional traded",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT t2.market_id, t2.side, sum(t2.price*t2.size) AS notional,\n SUM(CASE WHEN t2.side='long' THEN t2.price*t2.size ELSE -t2.price*t2.size END) AS net_notional,\n SUM(CASE WHEN t2.side='long' THEN t2.size ELSE -t2.size END) as net_size \nfrom \n(\n  SELECT * \n  FROM app_fill \n  WHERE profile_id in (13,14,15,1561,11002,11007,704,11831) \n  and timestamp >= $__from::bigint*1000\n) t1,\n(\n  SELECT * \n  FROM app_fill\n  WHERE profile_id in ($counter_party) \n  and timestamp >= $__from::bigint*1000\n) t2\nWHERE t2.trade_id=t1.trade_id\nGROUP BY t2.market_id, t2.side;\n"
    }
   ]
  }
 ]
}