{
 "title": "Wallet Volume Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "wallet",
    "label": "wallet",
    "query": "0xc30b96c4ed135c318e71c1b57425f06e05bed37a"
   }
  ]
 },
 "panels": [
  {
   "title": "7d Trading Volume by Wallet",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\ttime_bucket('7d'::interval,to_timestamp(bucket/1e6)) week, \r\n\tapp_profile.wallet,\r\n\tprofile_id, \r\n\tsum(volume) as volume \r\nFROM app_fill_1d \r\nJOIN app_profile ON app_fill_1d.profile_id = app_profile.id\r\nWHERE bucket >= (EXTRACT(EPOCH FROM now()-'7d'::interval) * 1000000)::bigint\r\nAND app_profile.wallet = lower('$wallet')\r\ngroup by week, app_profile.wallet, profile_id\r\nORDER BY week DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Profile ID Search",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT app_balance_operation.profile_id \nFROM app_balance_operation \nJOIN app_profile ON app_profile.id = app_balance_operation.profile_id\nWHERE app_profile.wallet=lower('$wallet')\nLIMIT 50"
    }
   ]
  },
  {
   "title": "30d Trading Volume by Wallet",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\ttime_bucket('1 month'::interval,to_timestamp(bucket/1e6)) as month, \r\n\tapp_profile.wallet,\r\n\tprofile_id, \r\n\tsum(volume) as volume \r\nFROM app_fill_1d \r\nJOIN app_profile ON app_fill_1d.profile_id = app_profile.id\r\nWHERE bucket >= (EXTRACT(EPOCH FROM now()-'30d'::interval) * 1000000)::bigint\r\nAND app_profile.wallet = lower('$wallet')\r\nGROUP BY 1,2,3\r\nORDER BY 1 DESC;\r\n"
    }
   ]
  },
  { "title": "Trading Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "30d Trading Volume by Wallet",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tapp_profile.wallet,\r\n\tprofile_id, \r\n\tsum(volume) as volume \r\nFROM app_fill_1d \r\nJOIN app_profile ON app_profile.id = app_fill_1d.profile_id\r\nWHERE bucket >= (EXTRACT(EPOCH FROM now()-'30d'::interval) * 1000000)::bigint\r\nGROUP BY 1,2;\r\n"
    }
   ]
  },
  {
   "title": "7d Trading Volume by Wallet",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tapp_profile.wallet,\r\n\tprofile_id, \r\n\tsum(volume) as volume \r\nFROM app_fill_1d \r\nJOIN app_profile ON app_profile.id = app_fill_1d.profile_id\r\nWHERE bucket >= (EXTRACT(EPOCH FROM now()-'7d'::interval) * 1000000)::bigint\r\nGROUP BY 1,2;\r\n"
    }
   ]
  },
  {
   "title": "Net Deposits by Wallet",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tapp_profile.wallet,\r\n\tprofile_id, \r\n\tSUM(net_deposit) AS net_deposit \r\nFROM app_balance_operation_net_deposit_1d \r\nJOIN app_profile ON app_profile.id = app_balance_operation_net_deposit_1d.profile_id\r\nGROUP BY 1,2;\r\n"
    }
   ]
  }
 ]
}