apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-websocket
  name: go-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-websocket
  template:
    metadata:
      labels:
        app: go-websocket
    spec:
      containers:
        - image: 618528691313.dkr.ecr.ap-northeast-1.amazonaws.com/rabbitx/go-websocket
          imagePullPolicy: Always
          command: ["/usr/bin/go-websocket"]
          name: go-websocket
          ports:
            - containerPort: 7778
              protocol: TCP
          resources: {}