apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-go-settlement
spec:
  provider: aws
  secretObjects:
    - secretName: settlement-secrets
      type: Opaque
      data:
        - objectName: "L1_OWNER_PRIVATE_KEY"
          key: L1_OWNER_PRIVATE_KEY
        - objectName: "ALCHEMY_URL"
          key: ALCHEMY_URL
        - objectName: "L2_SETTLER_ADDRESS"
          key: L2_SETTLER_ADDRESS
        - objectName: "L2_SETTLER_PRIVATE_KEY"
          key: L2_SETTLER_PRIVATE_KEY
  parameters:
    region: "ap-northeast-1"
    objects: |
      - objectName: "XXX"
        objectType: "secretsmanager"
        jmesPath:
            - path: "L1_OWNER_PRIVATE_KEY"
              objectAlias: "L1_OWNER_PRIVATE_KEY"
            - path: "ALCHEMY_URL"
              objectAlias: "ALCHEMY_URL"
            - path: "L2_SETTLER_ADDRESS"
              objectAlias: "L2_SETTLER_ADDRESS"
            - path: "L2_SETTLER_PRIVATE_KEY"
              objectAlias: "L2_SETTLER_PRIVATE_KEY"
