apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-slipstopper
  name: go-slipstopper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-slipstopper
  template:
    metadata:
      labels:
        app: go-slipstopper
    spec:
      containers:
        - image: 618528691313.dkr.ecr.ap-northeast-1.amazonaws.com/rabbitx/go-slipstopper
          imagePullPolicy: Always
          command: ["/usr/bin/go-slipstopper"]
          name: go-slipstopper
          resources: {}
