resources:
  - ../../base/

patchesJson6902:
  - target:
      kind: Deployment
      name: go-slipstopper
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 763292132769.dkr.ecr.ap-northeast-1.amazonaws.com/rabbitx-dev-apn1-testnet-go-slipstopper
