apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-go-pricing
spec:
  provider: aws
  secretObjects:
    - secretName: pricing-secrets
      type: Opaque
      data:
        - objectName: "COINGECKO_API_KEY"
          key: COINGECKO_API_KEY
        - objectName: "COINMARKETCAP_API_KEY"
          key: COINMARKETCAP_API_KEY
  parameters:
    region: "ap-northeast-1"
    objects: |
      - objectName: "XXX"
        objectType: "secretsmanager"
        jmesPath:
            - path: "COINGECKO_API_KEY"
              objectAlias: "COINGECKO_API_KEY"
            - path: "COINMARKETCAP_API_KEY"
              objectAlias: "COINMARKETCAP_API_KEY"
