apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-archiver
  name: go-archiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-archiver
  template:
    metadata:
      labels:
        app: go-archiver
    spec:
      containers:
        - image: 618528691313.dkr.ecr.ap-northeast-1.amazonaws.com/rabbitx/go-archiver
          imagePullPolicy: Always
          command: ["/usr/bin/go-archiver"]
          name: go-archiver
          resources: {}
