apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-liqengine
  name: go-liqengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-liqengine
  template:
    metadata:
      labels:
        app: go-liqengine
    spec:
      containers:
        - image: 618528691313.dkr.ecr.ap-northeast-1.amazonaws.com/rabbitx/go-liqengine
          imagePullPolicy: Always
          command: ["/usr/bin/go-liqengine"]
          name: go-liqengine
          resources: {}