resources:
  - ../../base/

patchesJson6902:
  - target:
      kind: Deployment
      name: go-pricingservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 618528691313.dkr.ecr.ap-northeast-1.amazonaws.com/rabbitx/go-pricingservice-prod

  - target:
      kind: SecretProviderClass
      name: aws-secrets-go-pricing
    patch: |-
      - op: replace
        path: /spec/parameters/objects
        value: |
          - objectName: "arn:aws:secretsmanager:ap-northeast-1:618528691313:secret:prod/go-pricingservice-OVI6kU"
            objectType: "secretsmanager"
            jmesPath:
                - path: "COINGECKO_API_KEY"
                  objectAlias: "COINGECKO_API_KEY"
                - path: "COINMARKETCAP_API_KEY"
                  objectAlias: "COINMARKETCAP_API_KEY"

  - target:
      kind: ServiceAccount
      name: pricing-service
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::618528691313:role/pricing-service-role-prod
