#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: grafana-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: ebs-sc-gp2
#  resources:
#    requests:
#      storage: 5Gi
