apiVersion: v1
kind: Service
metadata:
  labels:
    app: centrifugo
  name: centrifugo
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - protocol: TCP
      port: 10000
      targetPort: 10000
      name: grpc
  selector:
    app: centrifugo
  type: ClusterIP
