apiVersion: v1
kind: Service
metadata:
  labels:
    app: centrifugo
  name: centrifugo
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: centrifugo
  type: ClusterIP