apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-go-trading-bot
spec:
  parameters:
    objects: |-
      - objectName: "arn:aws:secretsmanager:ap-northeast-1:xxxxxxxxxxxx:secret:rabbitx-app-secret"
        objectType: "secretsmanager"
        jmesPath:
            - path: "BTC_PRIVATE_KEY"
              objectAlias: "BTC_PRIVATE_KEY"
            - path: "SOL_PRIVATE_KEY"
              objectAlias: "SOL_PRIVATE_KEY"
            - path: "ETH_PRIVATE_KEY"
              objectAlias: "ETH_PRIVATE_KEY"
            - path: "ARB_PRIVATE_KEY"
              objectAlias: "ARB_PRIVATE_KEY"
    region: ap-northeast-1
  provider: aws
  secretObjects:
    - data:
        - key: BTC_PRIVATE_KEY
          objectName: BTC_PRIVATE_KEY
        - key: SOL_PRIVATE_KEY
          objectName: SOL_PRIVATE_KEY
        - key: ETH_PRIVATE_KEY
          objectName: ETH_PRIVATE_KEY
        - key: ARB_PRIVATE_KEY
          objectName: ARB_PRIVATE_KEY
      secretName: trading-bot-secrets
      type: Opaque
