apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-go-api
spec:
  provider: aws
  secretObjects:
    - secretName: go-api-secrets
      type: Opaque
      data:
        - objectName: "ALCHEMY_URL"
          key: ALCHEMY_URL
        - objectName: "BLAST_OPERATOR_PRIV_KEY"
          key: BLAST_OPERATOR_PRIV_KEY
  parameters:
    region: "ap-northeast-1"
    objects: |
      - objectName: "XXX"
        objectType: "secretsmanager"
        jmesPath:
            - path: "ALCHEMY_URL"
              objectAlias: "ALCHEMY_URL"
            - path: "BLAST_OPERATOR_PRIV_KEY"
              objectAlias: "BLAST_OPERATOR_PRIV_KEY"
