apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-api
  name: go-api
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: go-api
  type: ClusterIP
