resources:
  - ../../base/

patchesJson6902:
  - target:
      kind: Deployment
      name: go-trading-bot
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: 763292132769.dkr.ecr.ap-northeast-1.amazonaws.com/rabbitx-dev-apn1-testnet-go-trading-bot

  - target:
      kind: SecretProviderClass
      name: aws-secrets-go-trading-bot
    patch: |-
      - op: replace
        path: /spec/parameters/objects
        value: |
          - objectName: "arn:aws:secretsmanager:ap-northeast-1:763292132769:secret:rabbitx-dev-apn1-testnet-go-trading-bot-xDehjq"
            objectType: "secretsmanager"
            jmesPath:
              - path: "BTC_PRIVATE_KEY"
                objectAlias: "BTC_PRIVATE_KEY"
              - path: "SOL_PRIVATE_KEY"
                objectAlias: "SOL_PRIVATE_KEY"
              - path: "ETH_PRIVATE_KEY"
                objectAlias: "ETH_PRIVATE_KEY"
              - path: "ARB_PRIVATE_KEY"
                objectAlias: "ARB_PRIVATE_KEY"

  - target:
      kind: ServiceAccount
      name: go-trading-bot-service
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::763292132769:role/rabbitx-dev-apn1-testnet-eks-service-go-trading-bot
