test-all:
	go test . -count=1 -tags=go_tarantool_msgpack_v5 -v

test-withdraw:
	go test . -count=1 -tags=go_tarantool_msgpack_v5 -run "TestWithdraw*" -v

test-claimops-response:
	go test . -count=1 -tags=go_tarantool_msgpack_v5 -run "TestClaimOpsResponse*" -v

